// 节假日数据库 - 中国 + Keeta 海外市场
// 覆盖年份：2026 / 2027
// 中东国家伊斯兰节日日期以官方公告为准，本数据为预估

const HOLIDAYS_DATA = {
  CN: {
    2026: [
      { date: "2026-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2026-02-17", name: { zh: "春节", en: "Chinese New Year", pt: "Ano Novo Chinês", ar: "رأس السنة الصينية" } },
      { date: "2026-02-18", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2026-02-19", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2026-02-20", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2026-02-21", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2026-02-22", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2026-02-23", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2026-04-05", name: { zh: "清明节", en: "Qingming Festival", pt: "Festival Qingming", ar: "مهرجان تشينغمينغ" } },
      { date: "2026-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2026-05-02", name: { zh: "劳动节假期", en: "Labour Day Holiday", pt: "Feriado do Trabalho", ar: "عطلة عيد العمال" } },
      { date: "2026-05-03", name: { zh: "劳动节假期", en: "Labour Day Holiday", pt: "Feriado do Trabalho", ar: "عطلة عيد العمال" } },
      { date: "2026-06-19", name: { zh: "端午节", en: "Dragon Boat Festival", pt: "Festival do Barco Dragão", ar: "مهرجان قوارب التنين" } },
      { date: "2026-06-20", name: { zh: "端午假期", en: "Dragon Boat Holiday", pt: "Feriado Barco Dragão", ar: "عطلة مهرجان قوارب التنين" } },
      { date: "2026-06-21", name: { zh: "端午假期", en: "Dragon Boat Holiday", pt: "Feriado Barco Dragão", ar: "عطلة مهرجان قوارب التنين" } },
      { date: "2026-09-25", name: { zh: "中秋节", en: "Mid-Autumn Festival", pt: "Festival do Meio Outono", ar: "مهرجان منتصف الخريف" } },
      { date: "2026-10-01", name: { zh: "国庆节", en: "National Day", pt: "Dia Nacional", ar: "اليوم الوطني" } },
      { date: "2026-10-02", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2026-10-03", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2026-10-04", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2026-10-05", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2026-10-06", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2026-10-07", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
    ],
    2027: [
      { date: "2027-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2027-02-06", name: { zh: "春节", en: "Chinese New Year", pt: "Ano Novo Chinês", ar: "رأس السنة الصينية" } },
      { date: "2027-02-07", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2027-02-08", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2027-02-09", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2027-02-10", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2027-02-11", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2027-02-12", name: { zh: "春节假期", en: "Spring Festival Holiday", pt: "Feriado Ano Novo Chinês", ar: "عطلة رأس السنة الصينية" } },
      { date: "2027-04-05", name: { zh: "清明节", en: "Qingming Festival", pt: "Festival Qingming", ar: "مهرجان تشينغمينغ" } },
      { date: "2027-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2027-05-02", name: { zh: "劳动节假期", en: "Labour Day Holiday", pt: "Feriado do Trabalho", ar: "عطلة عيد العمال" } },
      { date: "2027-05-03", name: { zh: "劳动节假期", en: "Labour Day Holiday", pt: "Feriado do Trabalho", ar: "عطلة عيد العمال" } },
      { date: "2027-06-09", name: { zh: "端午节", en: "Dragon Boat Festival", pt: "Festival do Barco Dragão", ar: "مهرجان قوارب التنين" } },
      { date: "2027-06-10", name: { zh: "端午假期", en: "Dragon Boat Holiday", pt: "Feriado Barco Dragão", ar: "عطلة مهرجان قوارب التنين" } },
      { date: "2027-06-11", name: { zh: "端午假期", en: "Dragon Boat Holiday", pt: "Feriado Barco Dragão", ar: "عطلة مهرجان قوارب التنين" } },
      { date: "2027-10-01", name: { zh: "国庆节", en: "National Day", pt: "Dia Nacional", ar: "اليوم الوطني" } },
      { date: "2027-10-02", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2027-10-03", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2027-10-04", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2027-10-05", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2027-10-06", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2027-10-07", name: { zh: "国庆假期", en: "National Day Holiday", pt: "Feriado Nacional", ar: "عطلة اليوم الوطني" } },
      { date: "2027-10-14", name: { zh: "中秋节", en: "Mid-Autumn Festival", pt: "Festival do Meio Outono", ar: "مهرجان منتصف الخريف" } },
    ]
  },
  BR: {
    2026: [
      { date: "2026-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Confraternização Universal", ar: "رأس السنة الميلادية" } },
      { date: "2026-02-16", name: { zh: "狂欢节", en: "Carnival Monday", pt: "Carnaval", ar: "كرنفال" } },
      { date: "2026-02-17", name: { zh: "狂欢节", en: "Carnival Tuesday", pt: "Carnaval", ar: "كرنفال" } },
      { date: "2026-04-03", name: { zh: "耶稣受难日", en: "Good Friday", pt: "Sexta-feira Santa", ar: "الجمعة العظيمة" } },
      { date: "2026-04-21", name: { zh: "提拉丹提斯日", en: "Tiradentes Day", pt: "Dia de Tiradentes", ar: "يوم تيرادينتيس" } },
      { date: "2026-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2026-06-04", name: { zh: "基督圣体节", en: "Corpus Christi", pt: "Corpus Christi", ar: "عيد جسد المسيح" } },
      { date: "2026-09-07", name: { zh: "独立日", en: "Independence Day", pt: "Dia da Independência", ar: "يوم الاستقلال" } },
      { date: "2026-10-12", name: { zh: "圣母显灵节", en: "Our Lady of Aparecida", pt: "Nossa Senhora Aparecida", ar: "سيدتنا أباريسيدا" } },
      { date: "2026-11-02", name: { zh: "万灵节", en: "All Souls' Day", pt: "Finados", ar: "يوم الأرواح" } },
      { date: "2026-11-15", name: { zh: "共和国宣告日", en: "Republic Day", pt: "Proclamação da República", ar: "يوم الجمهورية" } },
      { date: "2026-11-20", name: { zh: "黑人意识日", en: "Black Consciousness Day", pt: "Dia da Consciência Negra", ar: "يوم الوعي الأسود" } },
      { date: "2026-12-25", name: { zh: "圣诞节", en: "Christmas Day", pt: "Natal", ar: "عيد الميلاد" } },
    ],
    2027: [
      { date: "2027-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Confraternização Universal", ar: "رأس السنة الميلادية" } },
      { date: "2027-02-08", name: { zh: "狂欢节", en: "Carnival Monday", pt: "Carnaval", ar: "كرنفال" } },
      { date: "2027-02-09", name: { zh: "狂欢节", en: "Carnival Tuesday", pt: "Carnaval", ar: "كرنفال" } },
      { date: "2027-03-26", name: { zh: "耶稣受难日", en: "Good Friday", pt: "Sexta-feira Santa", ar: "الجمعة العظيمة" } },
      { date: "2027-04-21", name: { zh: "提拉丹提斯日", en: "Tiradentes Day", pt: "Dia de Tiradentes", ar: "يوم تيرادينتيس" } },
      { date: "2027-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2027-05-27", name: { zh: "基督圣体节", en: "Corpus Christi", pt: "Corpus Christi", ar: "عيد جسد المسيح" } },
      { date: "2027-09-07", name: { zh: "独立日", en: "Independence Day", pt: "Dia da Independência", ar: "يوم الاستقلال" } },
      { date: "2027-10-12", name: { zh: "圣母显灵节", en: "Our Lady of Aparecida", pt: "Nossa Senhora Aparecida", ar: "سيدتنا أباريسيدا" } },
      { date: "2027-11-02", name: { zh: "万灵节", en: "All Souls' Day", pt: "Finados", ar: "يوم الأرواح" } },
      { date: "2027-11-15", name: { zh: "共和国宣告日", en: "Republic Day", pt: "Proclamação da República", ar: "يوم الجمهورية" } },
      { date: "2027-11-20", name: { zh: "黑人意识日", en: "Black Consciousness Day", pt: "Dia da Consciência Negra", ar: "يوم الوعي الأسود" } },
      { date: "2027-12-25", name: { zh: "圣诞节", en: "Christmas Day", pt: "Natal", ar: "عيد الميلاد" } },
    ]
  },
  HK: {
    2026: [
      { date: "2026-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2026-02-17", name: { zh: "农历年初一", en: "Lunar New Year", pt: "Ano Novo Lunar", ar: "رأس السنة القمرية" } },
      { date: "2026-02-18", name: { zh: "农历年初二", en: "Lunar New Year (2nd)", pt: "2º Dia Ano Novo Lunar", ar: "اليوم الثاني من السنة القمرية" } },
      { date: "2026-02-19", name: { zh: "农历年初三", en: "Lunar New Year (3rd)", pt: "3º Dia Ano Novo Lunar", ar: "اليوم الثالث من السنة القمرية" } },
      { date: "2026-04-03", name: { zh: "耶稣受难日", en: "Good Friday", pt: "Sexta-feira Santa", ar: "الجمعة العظيمة" } },
      { date: "2026-04-04", name: { zh: "清明节", en: "Ching Ming Festival", pt: "Festival Ching Ming", ar: "مهرجان تشينغ مينغ" } },
      { date: "2026-04-06", name: { zh: "复活节星期一", en: "Easter Monday", pt: "Segunda-feira de Páscoa", ar: "اثنين الفصح" } },
      { date: "2026-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2026-05-24", name: { zh: "佛诞", en: "Buddha's Birthday", pt: "Aniversário de Buda", ar: "عيد ميلاد بوذا" } },
      { date: "2026-06-20", name: { zh: "端午节", en: "Tuen Ng Festival", pt: "Festival Tuen Ng", ar: "مهرجان تيون نغ" } },
      { date: "2026-07-01", name: { zh: "回归纪念日", en: "HKSAR Establishment Day", pt: "Dia da RAEHK", ar: "يوم تأسيس هونغ كونغ" } },
      { date: "2026-10-01", name: { zh: "国庆日", en: "National Day", pt: "Dia Nacional", ar: "اليوم الوطني" } },
      { date: "2026-10-02", name: { zh: "中秋节翌日", en: "Day after Mid-Autumn", pt: "Dia após Meio Outono", ar: "اليوم التالي لمهرجان منتصف الخريف" } },
      { date: "2026-10-18", name: { zh: "重阳节", en: "Chung Yeung Festival", pt: "Festival Chung Yeung", ar: "مهرجان تشونغ يونغ" } },
      { date: "2026-12-25", name: { zh: "圣诞节", en: "Christmas Day", pt: "Natal", ar: "عيد الميلاد" } },
      { date: "2026-12-26", name: { zh: "节礼日", en: "Boxing Day", pt: "Dia de Boxing", ar: "يوم الملاكمة" } },
    ],
    2027: [
      { date: "2027-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2027-02-06", name: { zh: "农历年初一", en: "Lunar New Year", pt: "Ano Novo Lunar", ar: "رأس السنة القمرية" } },
      { date: "2027-02-07", name: { zh: "农历年初二", en: "Lunar New Year (2nd)", pt: "2º Dia Ano Novo Lunar", ar: "اليوم الثاني من السنة القمرية" } },
      { date: "2027-02-08", name: { zh: "农历年初三", en: "Lunar New Year (3rd)", pt: "3º Dia Ano Novo Lunar", ar: "اليوم الثالث من السنة القمرية" } },
      { date: "2027-03-26", name: { zh: "耶稣受难日", en: "Good Friday", pt: "Sexta-feira Santa", ar: "الجمعة العظيمة" } },
      { date: "2027-03-27", name: { zh: "受难日翌日", en: "Day after Good Friday", pt: "Dia após Sexta-feira Santa", ar: "اليوم التالي للجمعة العظيمة" } },
      { date: "2027-03-29", name: { zh: "复活节星期一", en: "Easter Monday", pt: "Segunda-feira de Páscoa", ar: "اثنين الفصح" } },
      { date: "2027-04-05", name: { zh: "清明节", en: "Ching Ming Festival", pt: "Festival Ching Ming", ar: "مهرجان تشينغ مينغ" } },
      { date: "2027-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2027-05-13", name: { zh: "佛诞", en: "Buddha's Birthday", pt: "Aniversário de Buda", ar: "عيد ميلاد بوذا" } },
      { date: "2027-06-09", name: { zh: "端午节", en: "Tuen Ng Festival", pt: "Festival Tuen Ng", ar: "مهرجان تيون نغ" } },
      { date: "2027-07-01", name: { zh: "回归纪念日", en: "HKSAR Establishment Day", pt: "Dia da RAEHK", ar: "يوم تأسيس هونغ كونغ" } },
      { date: "2027-10-01", name: { zh: "国庆日", en: "National Day", pt: "Dia Nacional", ar: "اليوم الوطني" } },
      { date: "2027-10-15", name: { zh: "中秋节翌日", en: "Day after Mid-Autumn", pt: "Dia após Meio Outono", ar: "اليوم التالي لمهرجان منتصف الخريف" } },
      { date: "2027-10-26", name: { zh: "重阳节", en: "Chung Yeung Festival", pt: "Festival Chung Yeung", ar: "مهرجان تشونغ يونغ" } },
      { date: "2027-12-25", name: { zh: "圣诞节", en: "Christmas Day", pt: "Natal", ar: "عيد الميلاد" } },
      { date: "2027-12-27", name: { zh: "节礼日(补假)", en: "Boxing Day (substitute)", pt: "Dia de Boxing (substituto)", ar: "يوم الملاكمة (بديل)" } },
    ]
  },
  SA: {
    2026: [
      { date: "2026-02-22", name: { zh: "建国日", en: "Saudi Founding Day", pt: "Dia de Fundação", ar: "يوم التأسيس السعودي" } },
      { date: "2026-03-19", name: { zh: "开斋节假期", en: "Eid Al-Fitr Eve", pt: "Véspera de Eid Al-Fitr", ar: "ليلة عيد الفطر" } },
      { date: "2026-03-20", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2026-03-21", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2026-03-22", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2026-03-23", name: { zh: "开斋节假期", en: "Eid Al-Fitr Holiday", pt: "Feriado de Eid Al-Fitr", ar: "عطلة عيد الفطر" } },
      { date: "2026-05-26", name: { zh: "宰牲节假期", en: "Eid Al-Adha Eve", pt: "Véspera de Eid Al-Adha", ar: "ليلة عيد الأضحى" } },
      { date: "2026-05-27", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2026-05-28", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2026-05-29", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2026-05-30", name: { zh: "宰牲节假期", en: "Eid Al-Adha Holiday", pt: "Feriado de Eid Al-Adha", ar: "عطلة عيد الأضحى" } },
      { date: "2026-09-23", name: { zh: "国庆节", en: "Saudi National Day", pt: "Dia Nacional Saudita", ar: "اليوم الوطني السعودي" } },
    ],
    2027: [
      { date: "2027-02-22", name: { zh: "建国日", en: "Saudi Founding Day", pt: "Dia de Fundação", ar: "يوم التأسيس السعودي" } },
      { date: "2027-03-08", name: { zh: "开斋节假期", en: "Eid Al-Fitr Eve", pt: "Véspera de Eid Al-Fitr", ar: "ليلة عيد الفطر" } },
      { date: "2027-03-09", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2027-03-10", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2027-03-11", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2027-03-12", name: { zh: "开斋节假期", en: "Eid Al-Fitr Holiday", pt: "Feriado de Eid Al-Fitr", ar: "عطلة عيد الفطر" } },
      { date: "2027-05-15", name: { zh: "宰牲节假期", en: "Eid Al-Adha Eve", pt: "Véspera de Eid Al-Adha", ar: "ليلة عيد الأضحى" } },
      { date: "2027-05-16", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2027-05-17", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2027-05-18", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2027-05-19", name: { zh: "宰牲节假期", en: "Eid Al-Adha Holiday", pt: "Feriado de Eid Al-Adha", ar: "عطلة عيد الأضحى" } },
      { date: "2027-09-23", name: { zh: "国庆节", en: "Saudi National Day", pt: "Dia Nacional Saudita", ar: "اليوم الوطني السعودي" } },
    ]
  },
  AE: {
    2026: [
      { date: "2026-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2026-03-20", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2026-03-21", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2026-03-22", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2026-05-27", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2026-05-28", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2026-05-29", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2026-06-16", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2026-08-25", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
      { date: "2026-11-28", name: { zh: "阿联酋国庆", en: "UAE National Day", pt: "Dia Nacional dos EAU", ar: "اليوم الوطني الإماراتي" } },
      { date: "2026-11-29", name: { zh: "国庆假期", en: "UAE National Day Holiday", pt: "Feriado Nacional dos EAU", ar: "عطلة اليوم الوطني الإماراتي" } },
    ],
    2027: [
      { date: "2027-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2027-03-09", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2027-03-10", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2027-03-11", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2027-05-16", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2027-05-17", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2027-05-18", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2027-06-05", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2027-08-14", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
      { date: "2027-11-28", name: { zh: "阿联酋国庆", en: "UAE National Day", pt: "Dia Nacional dos EAU", ar: "اليوم الوطني الإماراتي" } },
      { date: "2027-11-29", name: { zh: "国庆假期", en: "UAE National Day Holiday", pt: "Feriado Nacional dos EAU", ar: "عطلة اليوم الوطني الإماراتي" } },
    ]
  },
  QA: {
    2026: [
      { date: "2026-03-20", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2026-03-21", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2026-03-22", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2026-05-27", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2026-05-28", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2026-05-29", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2026-06-16", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2026-08-25", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
      { date: "2026-12-18", name: { zh: "卡塔尔国庆", en: "Qatar National Day", pt: "Dia Nacional do Catar", ar: "اليوم الوطني القطري" } },
    ],
    2027: [
      { date: "2027-03-09", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2027-03-10", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2027-03-11", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2027-05-16", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2027-05-17", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2027-05-18", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2027-06-05", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2027-08-14", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
      { date: "2027-12-18", name: { zh: "卡塔尔国庆", en: "Qatar National Day", pt: "Dia Nacional do Catar", ar: "اليوم الوطني القطري" } },
    ]
  },
  KW: {
    2026: [
      { date: "2026-02-25", name: { zh: "国庆节", en: "National Day", pt: "Dia Nacional do Kuwait", ar: "اليوم الوطني الكويتي" } },
      { date: "2026-02-26", name: { zh: "解放日", en: "Liberation Day", pt: "Dia da Libertação", ar: "يوم التحرير" } },
      { date: "2026-03-20", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2026-03-21", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2026-03-22", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2026-05-27", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2026-05-28", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2026-05-29", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2026-06-16", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2026-08-25", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
    ],
    2027: [
      { date: "2027-02-25", name: { zh: "国庆节", en: "National Day", pt: "Dia Nacional do Kuwait", ar: "اليوم الوطني الكويتي" } },
      { date: "2027-02-26", name: { zh: "解放日", en: "Liberation Day", pt: "Dia da Libertação", ar: "يوم التحرير" } },
      { date: "2027-03-09", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2027-03-10", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2027-03-11", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2027-05-16", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2027-05-17", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2027-05-18", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2027-06-05", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2027-08-14", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
    ]
  },
  BH: {
    2026: [
      { date: "2026-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2026-03-20", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2026-03-21", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2026-03-22", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2026-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2026-05-27", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2026-05-28", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2026-05-29", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2026-06-16", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2026-08-25", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
      { date: "2026-12-16", name: { zh: "国庆节", en: "Bahrain National Day", pt: "Dia Nacional do Bahrein", ar: "اليوم الوطني البحريني" } },
      { date: "2026-12-17", name: { zh: "国庆假期", en: "Bahrain National Day Holiday", pt: "Feriado Nacional do Bahrein", ar: "عطلة اليوم الوطني البحريني" } },
    ],
    2027: [
      { date: "2027-01-01", name: { zh: "元旦", en: "New Year's Day", pt: "Ano Novo", ar: "رأس السنة الميلادية" } },
      { date: "2027-03-09", name: { zh: "开斋节", en: "Eid Al-Fitr", pt: "Eid Al-Fitr", ar: "عيد الفطر" } },
      { date: "2027-03-10", name: { zh: "开斋节", en: "Eid Al-Fitr (2nd)", pt: "Eid Al-Fitr (2º Dia)", ar: "عيد الفطر (اليوم الثاني)" } },
      { date: "2027-03-11", name: { zh: "开斋节", en: "Eid Al-Fitr (3rd)", pt: "Eid Al-Fitr (3º Dia)", ar: "عيد الفطر (اليوم الثالث)" } },
      { date: "2027-05-01", name: { zh: "劳动节", en: "Labour Day", pt: "Dia do Trabalho", ar: "عيد العمال" } },
      { date: "2027-05-16", name: { zh: "宰牲节", en: "Eid Al-Adha", pt: "Eid Al-Adha", ar: "عيد الأضحى" } },
      { date: "2027-05-17", name: { zh: "宰牲节", en: "Eid Al-Adha (2nd)", pt: "Eid Al-Adha (2º Dia)", ar: "عيد الأضحى (اليوم الثاني)" } },
      { date: "2027-05-18", name: { zh: "宰牲节", en: "Eid Al-Adha (3rd)", pt: "Eid Al-Adha (3º Dia)", ar: "عيد الأضحى (اليوم الثالث)" } },
      { date: "2027-06-05", name: { zh: "伊斯兰新年", en: "Islamic New Year", pt: "Ano Novo Islâmico", ar: "رأس السنة الهجرية" } },
      { date: "2027-08-14", name: { zh: "先知诞辰", en: "Prophet's Birthday", pt: "Aniversário do Profeta", ar: "المولد النبوي" } },
      { date: "2027-12-16", name: { zh: "国庆节", en: "Bahrain National Day", pt: "Dia Nacional do Bahrein", ar: "اليوم الوطني البحريني" } },
      { date: "2027-12-17", name: { zh: "国庆假期", en: "Bahrain National Day Holiday", pt: "Feriado Nacional do Bahrein", ar: "عطلة اليوم الوطني البحريني" } },
    ]
  }
};
